### ISSUE TITLE
*blocks all inline javascript with 7-character-long random character strings*

### ISSUE THREAD

**Issue by SilicaAndPina** [null-dev/Anti-Anti-Adblock#1]
**yawn** or just unblock 1x1 images.. though that opens ya up to tracking..

tbh who even does <script type="text/javascript">function isajiasghiAIGGH(){}</script><

just look for that and remove it ^_^

id make an Anti-Anti-Anti-Adblock but i don wanna code atm

**Comment by null-dev** [comment]
TBH I actually have no idea what this code does exactly or how it works. I just did it as practice for converting PHP to JS. I haven't actually even tested/used it so...
